PROJECT = rootorium

CFLAGS = -DDEBUG -O0 -Wall -Wl,--build-id=none

obj-m += $(PROJECT).o

all:
	make -C /lib/modules/$(shell uname -r)/build M=$$PWD modules

clean:
	make -C /lib/modules/$(shell uname -r)/build M=$$PWD clean
